server:
  port: 9011
spring:
  datasource:
    url: jdbc:mysql://mysql.camp.training.com:3306/shop?characterEncoding=utf-8&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: hyx
    password: Hyx123!@#
    connectionTimeoutMilliseconds: 30000
    idleTimeoutMilliseconds: 60000
    maxLifetimeMilliseconds: 1800000
    maxPoolSize: 10
    minPoolSize: 1
    maintenanceIntervalMilliseconds: 30000
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        jdbc:
          batch_size: 100000
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        hbm2ddl:
          auto: none
    show-sql: true
#  druid:
#    web-stat-filter:
#      enabled: true
#      url-pattern: /*
#      exclusions: /*.js,/*.gif,/*.jpg,/*.bmp,/*.png,/*.css,/*.ico,/druid/*
#    filter:
#      stat:
#        enabled: true
#        log-slow-sql: true
#        slow-sql-millis: 10000
#        merge-sql: true
#    aop-patterns: com.demo.shire.*
#    stat-view-servlet:
#      login-password: root
#      login-username: root
  profiles:
    active:
