server:
  port: 9010
spring:
  datasource:
    username: root
    password: Hyx123!@#
    url: jdbc:mysql://aliyun:3306/cache?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: redis
  redis:
    host: localhost
    lettuce:
      pool:
        max-active: 16
        max-wait: 10ms

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.redis.model